# Generated by Django 6.0.2 on 2026-02-26 20:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo. Ej: 'Bogotá', 'Antioquia', 'Resto del país'",
                        max_length=100,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Nombre exacto de la ciudad. Vacío = aplica a todo el departamento.",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Departamento. Vacío = aplica a todo el país (default).",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo del envío en COP.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "free_shipping_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto mínimo de compra para envío gratis. Null = nunca gratis.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Días hábiles mínimos de entrega."
                    ),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Días hábiles máximos de entrega."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Tarifa de respaldo cuando no hay coincidencia por ciudad/departamento.",
                    ),
                ),
            ],
            options={
                "db_table": "shipping_rates",
                "ordering": ["department", "city"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_default", True)),
                        fields=("is_default",),
                        name="unique_active_default_shipping_rate",
                    )
                ],
            },
        ),
    ]
